NUMPY PART 1:

In [8]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [10]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [14]:
arr = np.array((1,2,3,4,55))
print(arr)
print(type(arr))

[ 1  2  3  4 55]
<class 'numpy.ndarray'>


DIMENSION IN ARRAY:

In [16]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


1 D ARRAY:

In [17]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr.ndim))

[1 2 3 4 5 6]
<class 'int'>


2 D ARRAY:

In [18]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr.ndim))

[[1 2 3]
 [4 5 6]]
<class 'int'>


In [19]:
arr = np.array([[1.1,2.2,3.3],[4.4,5.5,6.6]])
print(arr)
print(type(arr.ndim))

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
<class 'int'>


3 D ARRAY:

In [21]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(type(arr.ndim))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'int'>


CHECK NUMER OF DIMENSIONS:

In [22]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [23]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('2nd element on 1st row:', arr[0,1])

2nd element on 1st row: 20


In [24]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('4th element on 1st row:', arr[0,3])

4th element on 1st row: 40


ADD THE FIRST ELEMENT OF ROW 1 AND LAST ELEMENT:

In [25]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print('first element of 1st row:', arr[0,4])
print('last elememt of 2nd row:', arr[1,4])
print("sum is", arr[0,0]+arr[1,4])

first element of 1st row: 50
last elememt of 2nd row: 100
sum is 110


SLICING OF NUMPY ARRAYS:

In [26]:
import numpy as np

In [27]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [28]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


SLICING IN 2D ARRAY:

In [29]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [31]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[0,0:3])

[10 20 30]


CHECK9ING THE DATA TYPE OF AN ARRAY:

In [32]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [33]:
arr = np.array(['animals', 'bat', 'cat'])
print(arr.dtype)

<U7


CREATING ARRAYS WITH A DEFINED DATA TYPE:

In [34]:
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


CREATE AN ARRAY WITH DATA TYPES 4 BYTES INTEGER:

In [36]:
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


NUMPY ARRAY SHAPE:

PRINT THE SHAPE OF 2D ARRAY:

In [37]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [39]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr.shape)

(1, 3, 4)


JOINING NUMPY ARRAYS:

In [41]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


JOINING 2D ARRAY:

In [43]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2), axis =1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2), axis =0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


SPLITTING NUMPY ARRAYS:

SPLITING ARRAY IN 3 PARTS:

In [45]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


SPLITING THA ARRAY IN 4 PARTS:

In [46]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


RAVEL & FLATTEN:

CONVERTS MULTIDIMENTIONAL ARRAY INTO 1D ARRAY:

In [50]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is", m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [51]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is", m.ndim)
n = m.flatten()
print(n)
print("now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [52]:
c = np.array([[[[1,2,3],[78,37,65],[67,23,65]]]])
print(c)
print("the dimension is", c.ndim)
d = c.ravel()
print(d)
print("now the new dimension is", d.ndim)

[[[[ 1  2  3]
   [78 37 65]
   [67 23 65]]]]
the dimension is 4
[ 1  2  3 78 37 65 67 23 65]
now the new dimension is 1


In [53]:
c = np.array([[[[1,2,3],[78,37,65],[67,23,65]]]])
print(c)
print("the dimension is", c.ndim)
d = c.flatten()
print(d)
print("now the new dimension is", d.ndim)

[[[[ 1  2  3]
   [78 37 65]
   [67 23 65]]]]
the dimension is 4
[ 1  2  3 78 37 65 67 23 65]
now the new dimension is 1


UNIQUE FUNCTION:

In [56]:
k = np.array([1,2,4,6,3,22,4,64,24,6,3,1,44,654,3,5])
print(k)
x = np.unique(k)
print(x)

[  1   2   4   6   3  22   4  64  24   6   3   1  44 654   3   5]
[  1   2   3   4   5   6  22  24  44  64 654]


In [58]:
k = np.array([1,2,4,6,3,22,4,64,24,6,3,1,44,654,3,5])
print(k)
x = np.unique(k, return_index = True)
print(x)

[  1   2   4   6   3  22   4  64  24   6   3   1  44 654   3   5]
(array([  1,   2,   3,   4,   5,   6,  22,  24,  44,  64, 654]), array([ 0,  1,  4,  2, 15,  3,  5,  8, 12,  7, 13]))


DELETE:

In [59]:
a = np.array([12,34,4543,5,5,6,3])
d = np.delete(a,[2])
print(d)

[12 34  5  5  6  3]


In [65]:
x = np.array([[2,3,5,3,5,4],[6,3,56,2,5,6],[4,6,7,98,3,3]])
print(x)



[[ 2  3  5  3  5  4]
 [ 6  3 56  2  5  6]
 [ 4  6  7 98  3  3]]


In [66]:
x = np.array([[2,3,5,3,5,4],[6,3,56,2,5,6],[4,6,7,98,3,3]])
print(x)
print()
m = np.delete(x, 1, axis = 0)
print(m)

[[ 2  3  5  3  5  4]
 [ 6  3 56  2  5  6]
 [ 4  6  7 98  3  3]]

[[ 2  3  5  3  5  4]
 [ 4  6  7 98  3  3]]
